workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_id: com.aps.meetingcostcalculator
      vars:
        BUNDLE_ID: "com.aps.meetingcostcalculator"
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Setup Expo
        script: |
          npm install -g eas-cli
      - name: Build with EAS
        script: |
          eas build --platform ios --wait --non-interactive
    artifacts:
      - build/**/*.ipa
    publishing:
      email:
        recipients:
          - singleton33@yahoo.com
        notify:
          success: true
          failure: true
