workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build iOS app
        script: |
          npm install -g eas-cli
          eas build --platform ios --wait --non-interactive
    artifacts:
      - "**/*.ipa"
